# NeuroPilot 🚀 Default Configuration
# Centralized hyperparameters for training, validation, and loss calculation.
# Aligned with Ultralytics standards (Architecture vs. Training separation).

loss:
  lambda_det: 2.5     # Detection loss multiplier (from debug script)
  lambda_traj: 7.5   # Trajectory loss multiplier (from debug script)
  lambda_heatmap: 10.0 # Heatmap loss multiplier (from debug script)
  lambda_smooth: 0.1  # Smoothness loss multiplier
  lambda_cls: 1.0     # Classification loss multiplier (from debug script)
  lambda_gate: 0.5    # Command gating loss multiplier
  # FDAT Loss (Frenet-Decomposed Anisotropic Trajectory Loss)
  use_fdat: False             # Toggle: False = SmoothL1 (default), True = FDAT
  fdat_alpha_lane: 10.0       # Cross-track penalty weight (lane-following)
  fdat_beta_lane: 1.0         # Along-track penalty weight (lane-following)
  fdat_alpha_inter: 5.0       # Cross-track penalty weight (intersection)
  fdat_beta_inter: 3.0        # Along-track penalty weight (intersection)
  fdat_lambda_heading: 2.0    # Heading consistency weight
  fdat_lambda_endpoint: 5.0   # Endpoint anchor weight (intersection only)

trainer:
  max_epochs: 300
  learning_rate: 0.001       # initial learning rate (i.e. SGD=1E-2, Adam=1E-3)
  lr_final: 0.01            # final learning rate (lr0 * lrf)
  momentum: 0.937           # SGD momentum/Adam beta1
  weight_decay: 0.0005      # optimizer weight decay 5e-4
  warmup_epochs: 3.0        # warmup epochs (fractions ok)
  warmup_momentum: 0.8      # warmup initial momentum
  warmup_bias_lr: 0.01       # Reduced from 0.1 to avoid explosion with AdamW
  lr_schedule: "cosine"     # learning rate schedule
  use_amp: True
  use_ema: True
  ema_decay: 0.999
  checkpoint_top_k: 3       # Keep top k best weights
  early_stop_patience: 10   # Stop training if fitness stops improving
  grad_clip_norm: 10.0      # Gradient clipping threshold
  cmd_dropout_prob: 0.4     # Drop command to force visual learning
  experiment_name: "default"

data:
  image_size: 320
  batch_size: 32
  num_workers: 4
  augment:
    affine_prob: 0.5
    rotate_deg: 5.0
    translate: 0.1
    scale: 0.5
    shear: 0.2
    perspective_prob: 0.3
    perspective: 0.1
    hsv_prob: 0.5
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    color_jitter_prob: 0.5
    color_jitter: 0.3    # Random brightness and contrast intensity
    fliplr: 0.5
    mosaic: 1.0
    mixup: 1.0
    copy_paste: 0.0
    noise_prob: 0.2      # Probability of adding Gauss/ISO noise
    blur_prob: 0.1       # Probability of adding Motion/Gaussian blur

head:
  skip_heatmap_inference: False
